# -*- coding: utf-8 -*-
"""Mini case 2. (Tamara N. Elizondo Hernández)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDTaEhx49ran34VMd6I7qjNrlaLp7beV
"""

import seaborn as sns
import pandas as pd

# Include Any Additional Packages you need to import


# Load the "mpg" dataset from seaborn's GitHub repository
df = sns.load_dataset('mpg')

# Alternatively, you can load the "mpg" dataset directly from the UCI Machine Learning Repository:
# df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data', delim_whitespace=True, header=None, names=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name'])

# Print the first few rows of the dataset to verify that it's loaded correctly
df.head()

df.info()

df.describe()

import matplotlib.pyplot as plt
df.hist("weight")

plt.scatter(x= df.horsepower, y= df.weight)

import seaborn as sns
sns.pairplot(df)

"""Based on the calculations done. mpg and weight are the best candidates"""

df.corr()

sns.heatmap(df.corr())

"""There are different linear relations bertween  MPG and weight, for example and also some other variables like acceleration and mpg and model_year"""

X = df.weight
y = df.mpg

from sklearn.linear_model import LinearRegression

model = LinearRegression()

import statsmodels.api as sm
model = sm.OLS(y,X).fit()
model.predict (X)